/* The following code was generated by JFlex 1.6.1 */

package smpl.syntax.lexer;

/* Specification for SMPL tokens */

// user customisations
import java_cup.runtime.*;

import smpl.exceptions.TokenException;

import smpl.syntax.parser.sym;

// Jlex directives
    

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/smpl/syntax/lexer/SMPLLexer.jflex</tt>
 */
public class SMPLLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\2\1\3\1\1\1\67\1\7\1\22\22\0\1\3\1\21"+
    "\1\66\1\6\1\0\1\46\1\41\1\10\1\52\1\53\1\24\1\44"+
    "\1\56\1\45\1\16\1\23\2\62\10\5\1\51\1\57\1\17\1\20"+
    "\1\17\2\0\6\14\24\4\1\60\1\65\1\26\1\47\1\4\1\0"+
    "\1\36\1\61\1\13\1\40\1\15\1\12\1\4\1\32\1\33\2\4"+
    "\1\34\1\4\1\37\1\27\1\35\1\4\1\30\1\50\1\11\1\64"+
    "\1\4\1\31\1\63\2\4\1\54\1\42\1\55\1\43\6\0\1\67"+
    "\32\0\1\25\u15df\0\1\25\u097f\0\13\25\35\0\2\67\5\0\1\25"+
    "\57\0\1\25\u0fa0\0\1\25\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\2\0\3\1\1\5"+
    "\2\6\1\1\1\7\1\10\1\11\11\1\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\1\1\0\1\4\1\35\1\36\1\37\1\0"+
    "\1\40\3\0\3\1\1\35\1\6\1\41\1\1\1\42"+
    "\2\1\1\43\5\1\1\44\1\45\1\46\1\47\1\1"+
    "\2\0\1\4\1\35\1\50\1\51\1\52\1\53\1\54"+
    "\1\1\1\55\1\1\3\41\1\1\2\0\1\1\1\0"+
    "\3\1\1\56\2\1\1\57\1\60\1\61\4\62\1\63"+
    "\1\64\1\65\1\66\2\41\2\62\1\1\1\0\2\62"+
    "\2\0\1\41\1\1\1\67\1\1\1\70\1\1\2\71"+
    "\1\41\2\1\1\72\1\67\1\73\2\1\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\160\0\250\0\340\0\u0118"+
    "\0\u0150\0\u0188\0\u01c0\0\u01f8\0\u0230\0\u0268\0\160\0\u0268"+
    "\0\u02a0\0\160\0\u0150\0\u02d8\0\u0310\0\u0348\0\u0380\0\u03b8"+
    "\0\u03f0\0\u0428\0\u0460\0\u0498\0\160\0\160\0\160\0\160"+
    "\0\160\0\160\0\160\0\u04d0\0\250\0\u0150\0\250\0\u0150"+
    "\0\250\0\u0150\0\250\0\u0150\0\u0508\0\u0540\0\250\0\u0578"+
    "\0\u05b0\0\u05e8\0\u0620\0\u05b0\0\u05b0\0\u0658\0\u05b0\0\u0690"+
    "\0\u06c8\0\u0700\0\u0738\0\u0770\0\u07a8\0\u0578\0\u0578\0\u07e0"+
    "\0\u0818\0\u0578\0\u0850\0\u0888\0\u0578\0\u08c0\0\u08f8\0\u0930"+
    "\0\u0968\0\u09a0\0\u05b0\0\250\0\250\0\250\0\u09d8\0\u0a10"+
    "\0\u0a48\0\u0a80\0\u0ab8\0\u0a48\0\u0af0\0\u0b28\0\u0b60\0\u0b98"+
    "\0\u0bd0\0\u09d8\0\u0c08\0\u0a10\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8"+
    "\0\u0d20\0\u0d58\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\u09d8\0\u0e70"+
    "\0\u0ea8\0\u09d8\0\u09d8\0\u09d8\0\u0a10\0\u0ee0\0\250\0\u0f18"+
    "\0\u0a48\0\u0a48\0\u09d8\0\u09d8\0\250\0\u0f50\0\u0ce8\0\u0f88"+
    "\0\u0fc0\0\u0ff8\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u09d8\0\u10d8"+
    "\0\u1110\0\u1148\0\u09d8\0\u1180\0\250\0\u0ff8\0\u0a48\0\u11b8"+
    "\0\u11f0\0\u09d8\0\u1228\0\u09d8\0\u1260\0\u1298\0\u09d8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\3\1\7\1\10\1\6"+
    "\1\11\1\12\1\13\2\3\1\14\1\15\1\16\1\17"+
    "\1\20\1\4\1\21\1\22\1\0\1\23\1\24\1\25"+
    "\1\26\1\3\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\3"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\3\1\7\3\3\1\54\1\0\1\55\1\0\20\55"+
    "\1\0\42\55\1\56\1\57\1\55\1\60\1\0\1\60"+
    "\1\0\3\60\1\0\1\61\11\60\1\0\2\60\1\0"+
    "\1\61\22\60\10\61\5\60\1\61\71\0\1\60\1\0"+
    "\1\60\1\0\1\60\1\62\1\60\1\0\1\61\5\60"+
    "\1\63\3\60\1\0\2\60\1\0\1\61\22\60\10\61"+
    "\1\60\1\62\3\60\1\61\1\0\1\61\1\0\1\61"+
    "\1\0\3\61\1\0\1\61\1\64\1\65\1\66\1\61"+
    "\1\67\4\61\1\0\2\61\1\0\33\61\1\70\1\61"+
    "\1\71\1\72\2\61\1\0\1\61\1\0\1\61\1\0"+
    "\3\61\1\0\12\61\1\0\2\61\1\0\41\61\1\0"+
    "\1\60\1\0\1\60\1\0\3\60\1\0\1\61\11\60"+
    "\1\0\2\60\1\0\1\61\3\60\1\73\16\60\10\61"+
    "\5\60\1\61\1\0\1\60\1\0\1\60\1\0\3\60"+
    "\1\0\1\61\11\60\1\0\2\60\1\0\1\61\1\74"+
    "\21\60\10\61\5\60\1\61\1\0\1\60\1\0\1\60"+
    "\1\0\3\60\1\0\1\61\11\60\1\0\2\60\1\0"+
    "\1\61\5\60\1\75\14\60\10\61\5\60\1\61\1\0"+
    "\1\60\1\0\1\60\1\0\1\60\1\76\1\60\1\0"+
    "\1\61\11\60\1\0\2\60\1\0\1\61\22\60\10\61"+
    "\1\60\1\76\3\60\1\61\1\0\1\60\1\0\1\60"+
    "\1\0\3\60\1\0\1\61\7\60\1\77\1\60\1\0"+
    "\2\60\1\0\1\61\22\60\10\61\5\60\1\61\1\0"+
    "\1\60\1\0\1\60\1\0\3\60\1\0\1\61\11\60"+
    "\1\0\1\100\1\101\1\0\1\61\22\60\10\61\5\60"+
    "\1\61\1\0\1\60\1\0\1\60\1\0\3\60\1\0"+
    "\1\61\11\60\1\0\2\60\1\0\1\61\1\60\1\102"+
    "\20\60\10\61\5\60\1\61\1\0\1\60\1\0\1\60"+
    "\1\0\3\60\1\0\1\61\4\60\1\103\4\60\1\0"+
    "\2\60\1\0\1\61\22\60\10\61\5\60\1\61\1\0"+
    "\1\60\1\0\1\60\1\0\3\60\1\0\1\61\11\60"+
    "\1\0\2\60\1\0\1\61\3\60\1\104\16\60\10\61"+
    "\5\60\1\61\1\0\1\60\1\0\1\60\1\0\3\60"+
    "\1\0\1\61\1\60\1\105\7\60\1\0\2\60\1\0"+
    "\1\61\22\60\10\61\5\60\1\61\1\0\1\60\1\0"+
    "\1\60\1\0\3\60\1\0\1\61\4\60\1\106\4\60"+
    "\1\0\2\60\1\0\1\61\22\60\10\61\5\60\1\61"+
    "\1\0\1\60\1\0\1\60\1\0\3\60\1\0\1\61"+
    "\11\60\1\0\2\60\1\0\1\61\1\60\1\107\20\60"+
    "\10\61\5\60\1\61\1\0\1\60\1\0\1\60\1\0"+
    "\3\60\1\0\1\61\11\60\1\0\2\60\1\0\1\61"+
    "\10\60\1\110\11\60\10\61\5\60\1\61\1\0\1\60"+
    "\1\0\1\60\1\0\3\60\1\0\1\61\11\60\1\0"+
    "\2\60\1\0\1\61\1\111\21\60\10\61\5\60\1\61"+
    "\1\0\1\60\1\0\1\60\1\0\3\60\1\0\1\61"+
    "\4\60\1\112\4\60\1\0\2\60\1\0\1\61\22\60"+
    "\10\61\5\60\1\61\1\0\1\61\1\0\1\61\1\0"+
    "\3\61\1\0\10\61\1\113\1\61\1\0\2\61\1\0"+
    "\41\61\1\0\1\55\1\0\20\55\1\0\42\55\2\0"+
    "\1\55\11\0\1\114\25\0\1\115\26\0\1\116\1\0"+
    "\1\117\1\120\1\117\1\120\3\117\1\120\1\121\11\117"+
    "\1\120\2\117\1\120\1\61\22\117\2\121\1\61\1\121"+
    "\1\61\1\121\1\61\1\121\5\117\1\121\1\120\1\121"+
    "\1\120\1\121\1\120\3\121\1\120\12\121\1\120\2\121"+
    "\1\120\1\61\24\121\1\61\1\121\1\61\1\121\1\61"+
    "\7\121\1\120\1\117\1\120\1\117\1\120\1\117\1\122"+
    "\1\117\1\120\1\121\5\117\1\123\3\117\1\120\2\117"+
    "\1\120\1\61\22\117\2\121\1\61\1\121\1\61\1\121"+
    "\1\61\1\121\1\117\1\122\3\117\1\121\1\120\1\117"+
    "\1\120\1\117\1\120\1\117\1\123\1\117\1\120\1\121"+
    "\11\117\1\120\2\117\1\120\1\61\22\117\2\121\1\61"+
    "\1\121\1\61\1\121\1\61\1\121\1\117\1\123\3\117"+
    "\1\121\1\120\1\121\1\120\1\121\1\120\1\124\2\121"+
    "\1\120\1\121\5\124\4\121\1\120\2\121\1\120\1\61"+
    "\12\124\7\121\1\124\2\121\1\61\1\121\1\61\1\121"+
    "\1\61\1\121\1\124\1\121\2\124\1\125\1\121\1\120"+
    "\1\121\1\120\1\121\1\120\3\121\1\120\12\121\1\120"+
    "\2\121\1\120\1\61\24\121\1\61\1\121\1\61\1\121"+
    "\1\61\2\121\1\126\4\121\1\120\1\121\1\120\1\121"+
    "\1\120\1\121\1\127\1\121\1\120\2\121\4\127\4\121"+
    "\1\120\2\121\1\120\1\61\7\121\1\127\1\121\1\127"+
    "\12\121\1\61\1\121\1\61\1\121\1\61\1\121\2\127"+
    "\4\121\1\120\1\121\1\120\1\121\1\120\1\121\1\130"+
    "\1\121\1\120\2\121\4\130\4\121\1\120\2\121\1\120"+
    "\1\61\7\121\1\130\1\121\1\130\12\121\1\61\1\121"+
    "\1\61\1\121\1\61\1\121\2\130\4\121\1\120\1\117"+
    "\1\120\1\117\1\120\3\117\1\120\1\121\4\117\1\131"+
    "\4\117\1\120\2\117\1\120\1\61\22\117\2\121\1\61"+
    "\1\121\1\61\1\121\1\61\1\121\5\117\1\121\1\120"+
    "\1\117\1\120\1\117\1\120\3\117\1\120\1\121\11\117"+
    "\1\120\2\117\1\120\1\61\1\117\1\132\20\117\2\121"+
    "\1\61\1\121\1\61\1\121\1\61\1\121\5\117\1\121"+
    "\1\120\1\117\1\120\1\117\1\120\3\117\1\120\1\121"+
    "\11\117\1\120\2\117\1\120\1\61\21\117\1\133\2\121"+
    "\1\61\1\121\1\61\1\121\1\61\1\121\5\117\1\121"+
    "\1\120\1\100\1\134\1\100\1\135\3\100\1\135\12\100"+
    "\1\136\2\100\1\135\41\100\1\135\1\137\1\140\1\137"+
    "\1\140\3\137\1\140\1\141\11\137\1\140\1\137\1\142"+
    "\1\140\1\143\22\137\2\141\1\143\1\141\1\143\1\141"+
    "\1\143\1\141\5\137\1\141\1\140\1\117\1\120\1\117"+
    "\1\120\3\117\1\120\1\121\11\117\1\120\2\117\1\120"+
    "\1\61\6\117\1\144\1\145\12\117\2\121\1\61\1\121"+
    "\1\61\1\121\1\61\1\121\5\117\1\121\1\120\1\117"+
    "\1\120\1\117\1\120\3\117\1\120\1\121\11\117\1\120"+
    "\2\117\1\120\1\61\4\117\1\146\15\117\2\121\1\61"+
    "\1\121\1\61\1\121\1\61\1\121\5\117\1\121\1\120"+
    "\1\117\1\120\1\117\1\120\3\117\1\120\1\121\1\147"+
    "\10\117\1\120\2\117\1\120\1\61\22\117\2\121\1\61"+
    "\1\121\1\61\1\121\1\61\1\121\5\117\1\121\1\120"+
    "\1\117\1\120\1\117\1\120\3\117\1\120\1\121\11\117"+
    "\1\120\2\117\1\120\1\61\1\150\3\117\1\151\15\117"+
    "\2\121\1\61\1\121\1\61\1\121\1\61\1\121\5\117"+
    "\1\121\1\120\1\117\1\120\1\117\1\120\3\117\1\120"+
    "\1\121\11\117\1\120\2\117\1\120\1\61\11\117\1\152"+
    "\10\117\2\121\1\61\1\121\1\61\1\121\1\61\1\121"+
    "\5\117\1\121\1\120\1\117\1\120\1\117\1\120\3\117"+
    "\1\120\1\121\1\153\10\117\1\120\2\117\1\120\1\61"+
    "\22\117\2\121\1\61\1\121\1\61\1\121\1\61\1\121"+
    "\5\117\1\121\1\120\1\117\1\120\1\117\1\120\3\117"+
    "\1\120\1\121\1\117\1\154\7\117\1\120\2\117\1\120"+
    "\1\61\22\117\2\121\1\61\1\121\1\61\1\121\1\61"+
    "\1\121\5\117\1\121\1\120\1\117\1\155\1\117\1\120"+
    "\3\117\1\155\1\121\11\117\1\156\2\117\1\120\1\61"+
    "\22\117\2\121\1\61\1\121\1\61\1\121\1\61\1\121"+
    "\5\117\1\121\1\155\1\0\1\157\5\0\1\157\12\0"+
    "\1\160\44\0\1\157\1\121\1\155\1\121\1\120\3\121"+
    "\1\155\12\121\1\156\2\121\1\120\1\61\24\121\1\61"+
    "\1\121\1\61\1\121\1\61\7\121\1\155\1\117\1\155"+
    "\1\117\1\120\1\117\1\122\1\117\1\155\1\121\5\117"+
    "\1\123\3\117\1\156\2\117\1\120\1\61\22\117\2\121"+
    "\1\61\1\121\1\61\1\121\1\61\1\121\1\117\1\122"+
    "\3\117\1\121\1\155\1\117\1\155\1\117\1\120\1\117"+
    "\1\123\1\117\1\155\1\121\11\117\1\156\2\117\1\120"+
    "\1\61\22\117\2\121\1\61\1\121\1\61\1\121\1\61"+
    "\1\121\1\117\1\123\3\117\1\121\1\155\1\121\1\155"+
    "\1\121\1\120\3\121\1\155\1\121\1\161\10\121\1\156"+
    "\2\121\1\120\1\61\10\121\1\162\13\121\1\61\1\121"+
    "\1\61\1\121\1\61\7\121\1\155\1\121\1\155\1\121"+
    "\1\120\3\121\1\155\12\121\1\156\2\121\1\120\1\61"+
    "\24\121\1\61\1\121\1\61\1\121\1\61\2\121\1\126"+
    "\4\121\1\155\1\121\1\155\1\121\1\120\1\121\1\127"+
    "\1\121\1\155\2\121\4\127\4\121\1\156\2\121\1\120"+
    "\1\61\7\121\1\127\1\121\1\127\12\121\1\61\1\121"+
    "\1\61\1\121\1\61\1\121\2\127\4\121\1\155\1\121"+
    "\1\155\1\121\1\120\1\121\1\130\1\121\1\155\2\121"+
    "\4\130\4\121\1\156\2\121\1\120\1\61\7\121\1\130"+
    "\1\121\1\130\12\121\1\61\1\121\1\61\1\121\1\61"+
    "\1\121\2\130\4\121\1\155\1\117\1\155\1\117\1\120"+
    "\3\117\1\155\1\121\11\117\1\156\2\117\1\120\1\61"+
    "\10\117\1\163\11\117\2\121\1\61\1\121\1\61\1\121"+
    "\1\61\1\121\5\117\1\121\1\155\1\117\1\155\1\117"+
    "\1\120\3\117\1\155\1\121\4\117\1\164\4\117\1\156"+
    "\2\117\1\120\1\61\22\117\2\121\1\61\1\121\1\61"+
    "\1\121\1\61\1\121\5\117\1\121\1\155\1\135\1\165"+
    "\20\135\1\166\45\135\1\0\1\165\5\0\1\157\12\0"+
    "\1\160\44\0\1\157\1\137\1\167\1\137\1\140\3\137"+
    "\1\167\1\141\11\137\1\170\1\137\1\171\1\140\1\143"+
    "\22\137\2\141\1\143\1\141\1\143\1\141\1\143\1\141"+
    "\5\137\1\141\1\167\1\172\1\173\5\172\1\173\12\172"+
    "\1\174\1\172\1\175\42\172\1\173\1\141\1\167\1\141"+
    "\1\140\3\141\1\167\12\141\1\170\1\141\1\176\1\140"+
    "\1\143\24\141\1\143\1\141\1\143\1\141\1\143\7\141"+
    "\1\167\1\117\1\155\1\117\1\120\3\117\1\155\1\121"+
    "\11\117\1\156\1\177\1\142\1\120\1\61\22\117\2\121"+
    "\1\61\1\121\1\61\1\121\1\61\1\121\5\117\1\121"+
    "\1\155\1\141\1\140\1\141\1\140\3\141\1\140\12\141"+
    "\1\140\1\141\1\176\1\140\1\143\24\141\1\143\1\141"+
    "\1\143\1\141\1\143\7\141\1\140\1\117\1\155\1\117"+
    "\1\120\3\117\1\155\1\121\4\117\1\200\4\117\1\156"+
    "\2\117\1\120\1\61\22\117\2\121\1\61\1\121\1\61"+
    "\1\121\1\61\1\121\5\117\1\121\1\155\1\117\1\155"+
    "\1\117\1\120\3\117\1\155\1\121\11\117\1\156\2\117"+
    "\1\120\1\61\11\117\1\201\10\117\2\121\1\61\1\121"+
    "\1\61\1\121\1\61\1\121\5\117\1\121\1\155\1\117"+
    "\1\155\1\117\1\120\3\117\1\155\1\121\11\117\1\156"+
    "\2\117\1\120\1\61\5\117\1\202\14\117\2\121\1\61"+
    "\1\121\1\61\1\121\1\61\1\121\5\117\1\121\1\155"+
    "\1\117\1\155\1\117\1\120\3\117\1\155\1\121\2\117"+
    "\1\203\6\117\1\156\2\117\1\120\1\61\22\117\2\121"+
    "\1\61\1\121\1\61\1\121\1\61\1\121\5\117\1\121"+
    "\1\155\1\117\1\155\1\117\1\120\3\117\1\155\1\121"+
    "\11\117\1\156\2\117\1\120\1\61\10\117\1\204\11\117"+
    "\2\121\1\61\1\121\1\61\1\121\1\61\1\121\5\117"+
    "\1\121\1\155\1\0\1\205\5\0\1\157\12\0\1\160"+
    "\44\0\1\157\1\0\1\205\67\0\1\165\66\0\1\172"+
    "\1\206\5\172\1\173\12\172\1\174\1\172\1\175\42\172"+
    "\1\173\1\137\1\167\1\137\1\140\3\137\1\167\1\141"+
    "\11\137\1\170\1\177\1\171\1\140\1\143\22\137\2\141"+
    "\1\143\1\141\1\143\1\141\1\143\1\141\5\137\1\141"+
    "\1\167\24\172\1\175\44\172\1\206\22\172\1\175\66\172"+
    "\1\165\1\175\43\172\1\141\1\167\1\141\1\140\3\141"+
    "\1\167\12\141\1\170\1\207\1\176\1\140\1\143\24\141"+
    "\1\143\1\141\1\143\1\141\1\143\7\141\1\167\1\117"+
    "\1\155\1\117\1\120\3\117\1\155\1\121\11\117\1\156"+
    "\2\117\1\120\1\61\7\117\1\210\12\117\2\121\1\61"+
    "\1\121\1\61\1\121\1\61\1\121\5\117\1\121\1\155"+
    "\1\117\1\155\1\117\1\120\3\117\1\155\1\121\11\117"+
    "\1\156\2\117\1\120\1\61\4\117\1\211\15\117\2\121"+
    "\1\61\1\121\1\61\1\121\1\61\1\121\5\117\1\121"+
    "\1\155\1\117\1\155\1\117\1\120\3\117\1\155\1\121"+
    "\4\117\1\212\4\117\1\156\2\117\1\120\1\61\22\117"+
    "\2\121\1\61\1\121\1\61\1\121\1\61\1\121\5\117"+
    "\1\121\1\155\1\117\1\155\1\117\1\120\3\117\1\155"+
    "\1\121\1\213\10\117\1\156\2\117\1\120\1\61\22\117"+
    "\2\121\1\61\1\121\1\61\1\121\1\61\1\121\5\117"+
    "\1\121\1\155\1\117\1\155\1\117\1\120\3\117\1\155"+
    "\1\121\1\214\10\117\1\156\2\117\1\120\1\61\22\117"+
    "\2\121\1\61\1\121\1\61\1\121\1\61\1\121\5\117"+
    "\1\121\1\155\1\117\1\155\1\117\1\120\3\117\1\155"+
    "\1\121\11\117\1\156\2\117\1\120\1\61\10\117\1\215"+
    "\11\117\2\121\1\61\1\121\1\61\1\121\1\61\1\121"+
    "\5\117\1\121\1\155\1\117\1\155\1\117\1\120\3\117"+
    "\1\155\1\121\11\117\1\156\2\117\1\120\1\61\5\117"+
    "\1\216\14\117\2\121\1\61\1\121\1\61\1\121\1\61"+
    "\1\121\5\117\1\121\1\155\1\117\1\155\1\117\1\120"+
    "\3\117\1\155\1\121\1\217\10\117\1\156\2\117\1\120"+
    "\1\61\22\117\2\121\1\61\1\121\1\61\1\121\1\61"+
    "\1\121\5\117\1\121\1\155\1\117\1\155\1\117\1\120"+
    "\3\117\1\155\1\121\11\117\1\156\2\117\1\120\1\61"+
    "\10\117\1\217\11\117\2\121\1\61\1\121\1\61\1\121"+
    "\1\61\1\121\5\117\1\121\1\155";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4816];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\1\1\1\11\1\1\2\0\33\1"+
    "\1\11\1\1\1\11\1\1\1\11\1\1\1\11\3\1"+
    "\1\11\1\1\1\0\4\1\1\0\1\1\3\0\21\1"+
    "\3\11\1\1\2\0\16\1\2\0\1\1\1\0\13\1"+
    "\1\11\5\1\1\11\4\1\1\0\2\1\2\0\6\1"+
    "\1\11\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer string = new StringBuffer();

	public int getChar() {
	return yychar + 1;
    }

    public int getColumn() {
    	return yycolumn + 1;
    }

    public int getLine() {
	return yyline + 1;
    }

    public String getText() {
	return yytext();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public SMPLLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 202) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, TokenException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	return new Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [185] { // VAR"+ZZ_NL+"\t       return new Symbol(sym.VAR, yytext()); }");
            { // VAR
	       return new Symbol(sym.VAR, yytext());
            }
          case 60: break;
          case 2: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [101] { //skip newline, but reset char counter"+ZZ_NL+"\t\t\t yychar = 0; }");
            { //skip newline, but reset char counter
			 yychar = 0;
            }
          case 61: break;
          case 3: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [104] { // skip whitespace }");
            { // skip whitespace
            }
          case 62: break;
          case 4: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [158] { // INTEGER"+ZZ_NL+"\t       return new Symbol(sym.INT, "+ZZ_NL+"\t\t\t\t new Integer(yytext())); }");
            { // INTEGER
	       return new Symbol(sym.INT, 
				 new Integer(yytext()));
            }
          case 63: break;
          case 5: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [153] { return new Symbol(sym.PERIOD); }");
            { return new Symbol(sym.PERIOD);
            }
          case 64: break;
          case 6: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [115] { return new Symbol(sym.RELOP, yytext()); }");
            { return new Symbol(sym.RELOP, yytext());
            }
          case 65: break;
          case 7: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [129] { return new Symbol(sym.DIV); }");
            { return new Symbol(sym.DIV);
            }
          case 66: break;
          case 8: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [128] { return new Symbol(sym.MUL); }");
            { return new Symbol(sym.MUL);
            }
          case 67: break;
          case 9: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [155] { return new Symbol(sym.RSQUARE); }");
            { return new Symbol(sym.RSQUARE);
            }
          case 68: break;
          case 10: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [121] { return new Symbol(sym.BAND); }");
            { return new Symbol(sym.BAND);
            }
          case 69: break;
          case 11: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [122] { return new Symbol(sym.BOR); }");
            { return new Symbol(sym.BOR);
            }
          case 70: break;
          case 12: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [123] { return new Symbol(sym.NEG); }");
            { return new Symbol(sym.NEG);
            }
          case 71: break;
          case 13: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [126] { return new Symbol(sym.PLUS); }");
            { return new Symbol(sym.PLUS);
            }
          case 72: break;
          case 14: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [127] { return new Symbol(sym.MINUS); }");
            { return new Symbol(sym.MINUS);
            }
          case 73: break;
          case 15: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [130] { return new Symbol(sym.MOD); }");
            { return new Symbol(sym.MOD);
            }
          case 74: break;
          case 16: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [131] { return new Symbol(sym.POWER); }");
            { return new Symbol(sym.POWER);
            }
          case 75: break;
          case 17: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [151] { return new Symbol(sym.COLON); }");
            { return new Symbol(sym.COLON);
            }
          case 76: break;
          case 18: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [146] { return new Symbol(sym.LPAREN); }");
            { return new Symbol(sym.LPAREN);
            }
          case 77: break;
          case 19: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [147] { return new Symbol(sym.RPAREN); }");
            { return new Symbol(sym.RPAREN);
            }
          case 78: break;
          case 20: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [148] { return new Symbol(sym.LBRACE); }");
            { return new Symbol(sym.LBRACE);
            }
          case 79: break;
          case 21: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [149] { return new Symbol(sym.RBRACE); }");
            { return new Symbol(sym.RBRACE);
            }
          case 80: break;
          case 22: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [150] { return new Symbol(sym.COMMA); }");
            { return new Symbol(sym.COMMA);
            }
          case 81: break;
          case 23: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [152] { return new Symbol(sym.SEMI); }");
            { return new Symbol(sym.SEMI);
            }
          case 82: break;
          case 24: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [154] { return new Symbol(sym.LSQUARE); }");
            { return new Symbol(sym.LSQUARE);
            }
          case 83: break;
          case 25: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [219] { string.setLength(0); yybegin(STRING); }");
            { string.setLength(0); yybegin(STRING);
            }
          case 84: break;
          case 26: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [227] { string.append( yytext() ); }");
            { string.append( yytext() );
            }
          case 85: break;
          case 27: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [235] { string.append(\'\\\\\'); }");
            { string.append('\\');
            }
          case 86: break;
          case 28: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [223] { yybegin(YYINITIAL);"+ZZ_NL+"\t\t\t\t\t\treturn new Symbol(sym.STRING, string.toString()); }");
            { yybegin(YYINITIAL);
						return new Symbol(sym.STRING, string.toString());
            }
          case 87: break;
          case 29: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [164] { // REAL"+ZZ_NL+"\t\t\treturn new Symbol(sym.REAL,"+ZZ_NL+"\t\t\t\t new Double(yytext())); }");
            { // REAL
			return new Symbol(sym.REAL,
				 new Double(yytext()));
            }
          case 88: break;
          case 30: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [239] { return new Symbol(sym.TRUE, new Boolean(true)); }");
            { return new Symbol(sym.TRUE, new Boolean(true));
            }
          case 89: break;
          case 31: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [240] { return new Symbol(sym.FALSE, new Boolean(false)); }");
            { return new Symbol(sym.FALSE, new Boolean(false));
            }
          case 90: break;
          case 32: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [243] { return new Symbol(sym.NIL); }");
            { return new Symbol(sym.NIL);
            }
          case 91: break;
          case 33: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [141] { /* ignore */ }");
            { /* ignore */
            }
          case 92: break;
          case 34: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [117] { return new Symbol(sym.OR); }");
            { return new Symbol(sym.OR);
            }
          case 93: break;
          case 35: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [138] { return new Symbol(sym.IF); }");
            { return new Symbol(sym.IF);
            }
          case 94: break;
          case 36: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [145] { return new Symbol(sym.ASSIGN, yytext()); }");
            { return new Symbol(sym.ASSIGN, yytext());
            }
          case 95: break;
          case 37: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [229] { string.append(\'\\t\'); }");
            { string.append('\t');
            }
          case 96: break;
          case 38: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [231] { string.append(\'\\n\'); }");
            { string.append('\n');
            }
          case 97: break;
          case 39: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [233] { string.append(\'\\\"\'); }");
            { string.append('\"');
            }
          case 98: break;
          case 40: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [191] { // ChARACTER"+ZZ_NL+"\t\t\treturn new Symbol(sym.CHAR, yycharat(2)); }");
            { // ChARACTER
			return new Symbol(sym.CHAR, yycharat(2));
            }
          case 99: break;
          case 41: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [214] { //SPECIAL CHARACTERS"+ZZ_NL+"\t\t\treturn new Symbol(sym.CHAR, \'\\\\\'); }");
            { //SPECIAL CHARACTERS
			return new Symbol(sym.CHAR, '\\');
            }
          case 100: break;
          case 42: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [170] { // BINARY"+ZZ_NL+"\t\t\tString i = yytext().substring(2);"+ZZ_NL+"\t\t\treturn new Symbol(sym.INT,"+ZZ_NL+"\t\t\t\t Integer.parseInt(i, 2)); }");
            { // BINARY
			String i = yytext().substring(2);
			return new Symbol(sym.INT,
				 Integer.parseInt(i, 2));
            }
          case 101: break;
          case 43: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [177] { // HEX"+ZZ_NL+"\t\t\tString i = yytext().substring(2);"+ZZ_NL+"\t\t\treturn new Symbol(sym.INT,"+ZZ_NL+"\t\t\t\t Integer.parseInt(i,16)); }");
            { // HEX
			String i = yytext().substring(2);
			return new Symbol(sym.INT,
				 Integer.parseInt(i,16));
            }
          case 102: break;
          case 44: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [196] { //Unicode"+ZZ_NL+"\t\t\treturn new Symbol(sym.UNI, yytext().substring(2)); }");
            { //Unicode
			return new Symbol(sym.UNI, yytext().substring(2));
            }
          case 103: break;
          case 45: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [110] { return new Symbol(sym.FOR); }");
            { return new Symbol(sym.FOR);
            }
          case 104: break;
          case 46: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [136] { return new Symbol(sym.LET); }");
            { return new Symbol(sym.LET);
            }
          case 105: break;
          case 47: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [116] { return new Symbol(sym.AND); }");
            { return new Symbol(sym.AND);
            }
          case 106: break;
          case 48: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [118] { return new Symbol(sym.NOT); }");
            { return new Symbol(sym.NOT);
            }
          case 107: break;
          case 49: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [134] { return new Symbol(sym.DEF); }");
            { return new Symbol(sym.DEF);
            }
          case 108: break;
          case 50: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [248] { String msg = String.format(\"Unrecognised Token: %s\", yytext());"+ZZ_NL+"\t       throw new TokenException(msg); }");
            { String msg = String.format("Unrecognised Token: %s", yytext());
	       throw new TokenException(msg);
            }
          case 109: break;
          case 51: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [208] { //SPECIAL CHARACTERS"+ZZ_NL+"\t\t\treturn new Symbol(sym.CHAR, \'\\t\'); }");
            { //SPECIAL CHARACTERS
			return new Symbol(sym.CHAR, '\t');
            }
          case 110: break;
          case 52: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [202] { //SPECIAL CHARACTERS"+ZZ_NL+"\t\t\treturn new Symbol(sym.CHAR, \'\\n\'); }");
            { //SPECIAL CHARACTERS
			return new Symbol(sym.CHAR, '\n');
            }
          case 111: break;
          case 53: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [140] { return new Symbol(sym.THEN); }");
            { return new Symbol(sym.THEN);
            }
          case 112: break;
          case 54: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [139] { return new Symbol(sym.ELSE); }");
            { return new Symbol(sym.ELSE);
            }
          case 113: break;
          case 55: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [137] { return new Symbol(sym.IO, yytext()); }");
            { return new Symbol(sym.IO, yytext());
            }
          case 114: break;
          case 56: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [135] { return new Symbol(sym.PROC); }");
            { return new Symbol(sym.PROC);
            }
          case 115: break;
          case 57: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [248] { String msg = String.format(\"Unrecognised Token: %s\", yytext());"+ZZ_NL+"\t       throw new TokenException(msg); }");
            { String msg = String.format("Unrecognised Token: %s", yytext());
	       throw new TokenException(msg);
            }
          case 116: break;
          case 58: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [111] { return new Symbol(sym.WHILE); }");
            { return new Symbol(sym.WHILE);
            }
          case 117: break;
          case 59: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [112] { return new Symbol(sym.REPEAT); }");
            { return new Symbol(sym.REPEAT);
            }
          case 118: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java SMPLLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        SMPLLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new SMPLLexer(reader);
          do {
            System.out.println(scanner.next_token());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
