
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 02 17:38:47 EST 2020
//----------------------------------------------------

package smpl.syntax.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POWER = 22;
  public static final int CHAR = 34;
  public static final int PERIOD = 8;
  public static final int LPAREN = 2;
  public static final int SEMI = 7;
  public static final int REPEAT = 16;
  public static final int INT = 29;
  public static final int FOR = 14;
  public static final int MINUS = 18;
  public static final int RPAREN = 3;
  public static final int NOT = 28;
  public static final int AND = 26;
  public static final int NIL = 39;
  public static final int OR = 27;
  public static final int COMMA = 6;
  public static final int BAND = 23;
  public static final int DIV = 20;
  public static final int PLUS = 17;
  public static final int ASSIGN = 38;
  public static final int RELOP = 37;
  public static final int EOF = 0;
  public static final int TRUE = 32;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int MOD = 21;
  public static final int REAL = 31;
  public static final int NEG = 25;
  public static final int BOR = 24;
  public static final int LBRACE = 4;
  public static final int LSQUARE = 9;
  public static final int RSQUARE = 10;
  public static final int WHILE = 15;
  public static final int LET = 13;
  public static final int RBRACE = 5;
  public static final int STRING = 36;
  public static final int PROC = 12;
  public static final int DEF = 11;
  public static final int FALSE = 33;
  public static final int UNI = 35;
  public static final int VAR = 30;
}

