
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 02 12:00:57 EST 2020
//----------------------------------------------------

package smpl.syntax.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POWER = 23;
  public static final int CHAR = 35;
  public static final int PERIOD = 8;
  public static final int LPAREN = 2;
  public static final int SEMI = 7;
  public static final int INT = 30;
  public static final int MINUS = 19;
  public static final int RPAREN = 3;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int NIL = 40;
  public static final int OR = 28;
  public static final int COMMA = 6;
  public static final int BAND = 24;
  public static final int DIV = 21;
  public static final int PLUS = 18;
  public static final int ASSIGN = 39;
  public static final int IF = 15;
  public static final int RELOP = 38;
  public static final int EOF = 0;
  public static final int TRUE = 33;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int MOD = 22;
  public static final int REAL = 32;
  public static final int COLON = 9;
  public static final int NEG = 26;
  public static final int BOR = 25;
  public static final int LBRACE = 4;
  public static final int ELSE = 17;
  public static final int LSQUARE = 10;
  public static final int RSQUARE = 11;
  public static final int LET = 14;
  public static final int THEN = 16;
  public static final int RBRACE = 5;
  public static final int STRING = 37;
  public static final int PROC = 13;
  public static final int DEF = 12;
  public static final int FALSE = 34;
  public static final int UNI = 36;
  public static final int VAR = 31;
}

